server:
  port: 8080
  buffer: 10
  concurrency_limit: 100
  rate_limit: 100
  limiter_timeout: 10s
  timeout: 100s
dbconfig:
  mongouri: "mongodb://root:example@localhost:27017"
  db_name: "root"
  collection_name: "test"
  min_pool_size: 10
  max_pool_size: 100
